title: Tom J. Wilson
logo: pic.jpg
description: Postdoctoral fellow at STScI, working on PSF photometry in the astropy-affliated photutils package, and WFIRST supernovae survey optimisation. Astrostatistician, occasional exoplanet dabbler.
google analytics: UA-143824356-1
theme: jekyll-theme-minimal
